POST https://siga.congregacao.org.br/UTIL/UtilWS.asmx/ValidaPeriodo
Content-Type: application/json
Cookie: 
__antixsrftoken: b500c485e5e34b2da6b2fb06a952a640

{
  "f_data1": "01/07/2024",
  "f_data2": "31/07/2024",
  "l_data1": "Data Inicial",
  "l_data2": "Data Final"
}
