POST https://siga.congregacao.org.br/TES/TES00501.aspx
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAbhZulYrcw5YUD28
Cookie: 
Sec-Ch-Ua: "Chromium";v="127", "Not)A;Brand";v="99"
__antixsrftoken: b500c485e5e34b2da6b2fb06a952a640
Traceparent: 00-1fb13059aa98497ba33a080472a79a92-ef776834f4c849d4-01
Accept-Language: pt-BR
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.100 Safari/537.36
Accept: */*
X-Requested-With: XMLHttpRequest
Request-Id: |1fb13059aa98497ba33a080472a79a92.ef776834f4c849d4
Sec-Ch-Ua-Platform: "Linux"
Origin: https://siga.congregacao.org.br
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://siga.congregacao.org.br/TES/TES00501.aspx?f_inicio=S
Accept-Encoding: gzip, deflate, br
Priority: u=1, i

------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_consultar"

S
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_data1"

01/08/2024
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_data2"

31/08/2024
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_estabelecimento"


------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_filtro_relatorio"

345, 21329, 30670, 3836, 36426, 3837, 3960, 3782, 3982, 3838, 4376, 22888, 4090, 3824, 4373, 4252, 4466, 25197, 26389, 4164, 3983
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_formacontribuicao"

0
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_opcao2"

casaoracao
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_exibir"

comvalor
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_detalhar"

true
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_saidapara"

Excel
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="f_ordenacao"

alfabetica
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="__initPage__"

S
------WebKitFormBoundaryAbhZulYrcw5YUD28
Content-Disposition: form-data; name="__jqSubmit__"

S
------WebKitFormBoundaryAbhZulYrcw5YUD28--