POST https://siga.congregacao.org.br/TES/TES00507.aspx
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Language: pt-BR
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.100 Safari/537.36
Sec-Ch-Ua: "Chromium";v="127", "Not)A;Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Origin: https://siga.congregacao.org.br
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: iframe
Referer: https://siga.congregacao.org.br/TES/TES00501.aspx?f_inicio=S
Accept-Encoding: gzip, deflate, br
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Priority: u=0, i
Cookie: 

f_saidapara=Excel&__initPage__=S